# Generated by Django 5.2.6 on 2025-09-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadDailyPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masse', models.FloatField()),
                ('picked_area', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picked_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_id', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=13)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDailyPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masse', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CottonPicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm')),
            ],
        ),
        migrations.CreateModel(
            name='CarDailyPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.FloatField()),
                ('picked_area', models.FloatField()),
                ('cotton_masse', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cotton_picker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.cottonpicker')),
            ],
        ),
        migrations.CreateModel(
            name='Scalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqqm_id', models.IntegerField()),
                ('weight_checked', models.FloatField()),
                ('tech_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_number', models.BigIntegerField()),
                ('picking_type', models.CharField(choices=[('f', 'first'), ('s', 'second'), ('t', 'third'), ('fr', 'fourth')], max_length=100)),
                ('workers_count', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.neighborhood')),
            ],
        ),
    ]
