# Generated by Django 5.2.6 on 2025-09-10 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scalesman',
            name='squad_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.squad'),
        ),
        migrations.AddField(
            model_name='squaddailypicking',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.squad'),
        ),
        migrations.AddField(
            model_name='territory',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.squad'),
        ),
        migrations.AddField(
            model_name='cottonpicker',
            name='hudud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.territory'),
        ),
        migrations.AddField(
            model_name='worker',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.squad'),
        ),
        migrations.AddField(
            model_name='workerdailypicking',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.worker'),
        ),
    ]
