# Generated by Django 5.2.6 on 2025-09-11 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0012_alter_district_crop_area_alter_district_plan_and_more'),
        ('squad', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PQQM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SquadNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='squaddailypicking',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='squaddailypicking',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='scalesman',
            name='date',
        ),
        migrations.AddField(
            model_name='scalesman',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-10 16:25:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squaddailypicking',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('f', 'finished')], default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='squad',
            name='picking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.pickingtype'),
        ),
        migrations.AlterField(
            model_name='scalesman',
            name='pqqm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.pqqm'),
        ),
        migrations.CreateModel(
            name='Shtab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pickers', models.IntegerField()),
                ('workers_count', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm')),
                ('massive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.massive')),
                ('picking_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.pickingtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('squad_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.squadnumber')),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='shtab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.shtab'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='squad_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.squadnumber'),
        ),
    ]
