# Generated by Django 5.2.6 on 2025-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0003_pickingtype_pqqm_squadnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
