# Generated by Django 5.2.6 on 2025-09-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0004_squad_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadnumber',
            name='number',
            field=models.IntegerField(),
        ),
    ]
