# Generated by Django 5.2.6 on 2025-09-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0014_neighborhoodexcelupload_alter_neighborhood_crop_area'),
        ('squad', '0005_alter_squadnumber_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='farm',
        ),
        migrations.AddField(
            model_name='squaddailypicking',
            name='farm',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='region.farm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squaddailypicking',
            name='workers_count',
            field=models.IntegerField(default='111'),
            preserve_default=False,
        ),
    ]
