# Generated by Django 5.2.6 on 2025-09-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0006_remove_squad_farm_squaddailypicking_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/squad/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
