# Generated by Django 5.2.6 on 2025-09-12 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0007_squadexcelupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='shtab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squads_as_shtab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='squad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squads', to=settings.AUTH_USER_MODEL),
        ),
    ]
