# Generated by Django 5.2.6 on 2025-09-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0008_alter_squad_shtab_alter_squad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='squad_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squads', to='squad.squadnumber'),
        ),
    ]
