# Generated by Django 5.2.6 on 2025-09-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0016_alter_farm_district_alter_farm_massive_and_more'),
        ('squad', '0009_alter_squad_squad_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='squaddailypicking',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district'),
        ),
        migrations.AddField(
            model_name='squaddailypicking',
            name='massive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.massive'),
        ),
        migrations.AlterField(
            model_name='squaddailypicking',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.farm'),
        ),
    ]
