# Generated by Django 5.2.6 on 2025-09-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0009_alter_squad_squad_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='picking_type',
        ),
    ]
