# Generated by Django 5.2.6 on 2025-09-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0010_remove_squad_phone_number_remove_squad_picking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='workers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
