# Generated by Django 5.2.6 on 2025-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0010_squaddailypicking_district_squaddailypicking_massive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaddailypicking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='squaddailypicking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
