# Generated by Django 5.2.6 on 2025-09-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0011_alter_squaddailypicking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squaddailypicking',
            name='picking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squad.pickingtype'),
        ),
    ]
