# Generated by Django 5.2.6 on 2025-09-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0011_alter_squad_workers_count'),
        ('squad', '0012_squaddailypicking_picking_type'),
    ]

    operations = [
    ]
