# Generated by Django 5.2.6 on 2025-09-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0013_merge_20250912_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalesman',
            name='pqqm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqqms', to='squad.pqqm'),
        ),
        migrations.AlterField(
            model_name='scalesman',
            name='squad_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.squadnumber'),
        ),
        migrations.AlterField(
            model_name='scalesman',
            name='weight_checked',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
