# Generated by Django 5.2.6 on 2025-09-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0014_alter_scalesman_pqqm_id_alter_scalesman_squad_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scalesman',
            old_name='pqqm_id',
            new_name='pqqm',
        ),
    ]
