# Generated by Django 5.2.6 on 2025-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0015_rename_pqqm_id_scalesman_pqqm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaddailypicking',
            name='masse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
