# Generated by Django 5.2.6 on 2025-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0016_alter_squaddailypicking_masse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardailypicking',
            name='picked_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='squaddailypicking',
            name='picked_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='territory',
            name='picked_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
