# Generated by Django 5.2.6 on 2025-09-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0017_alter_cardailypicking_picked_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squaddailypicking',
            options={'ordering': ['-created_at', '-start_time']},
        ),
    ]
