# Generated by Django 5.2.6 on 2025-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0018_alter_squaddailypicking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaddailypicking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
