# Generated by Django 5.2.6 on 2025-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0019_alter_squaddailypicking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
