# Generated by Django 5.2.6 on 2025-09-13 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0016_alter_farm_district_alter_farm_massive_and_more'),
        ('squad', '0020_alter_squad_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardailypicking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cardailypicking',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='cottonpicker',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='cottonpicker',
            name='hudud',
        ),
        migrations.AddField(
            model_name='cardailypicking',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardailypicking',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.farm'),
        ),
        migrations.AddField(
            model_name='cardailypicking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cottonpicker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardailypicking',
            name='cotton_masse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cardailypicking',
            name='fuel',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cottonpicker',
            name='car_number',
            field=models.CharField(max_length=22),
        ),
    ]
