# Generated by Django 5.2.6 on 2025-09-13 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0021_remove_cardailypicking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardailypicking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardailypicking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardailypicking',
            name='fuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cardailypicking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
