# Generated by Django 5.2.6 on 2025-09-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0022_cardailypicking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardailypicking',
            name='cotton_picker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_dailies_picking', to='squad.cottonpicker'),
        ),
    ]
