# Generated by Django 5.2.6 on 2025-09-10 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm'),
        ),
        migrations.AddField(
            model_name='massive',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.district'),
        ),
        migrations.AddField(
            model_name='massive',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm'),
        ),
        migrations.AddField(
            model_name='massive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='massive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.massive'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.farm'),
        ),
        migrations.AddField(
            model_name='region',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region'),
        ),
    ]
