# Generated by Django 5.2.6 on 2025-09-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_alter_district_created_at_alter_massive_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='massive',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='region',
            name='farm',
        ),
        migrations.AddField(
            model_name='farm',
            name='claster',
            field=models.CharField(default='SULTON TEX GROUP MCHJ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='cotton_area',
            field=models.FloatField(default='23.3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district'),
        ),
        migrations.AddField(
            model_name='farm',
            name='gross_yield',
            field=models.FloatField(default='44'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='massive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.massive'),
        ),
        migrations.AddField(
            model_name='farm',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.neighborhood'),
        ),
        migrations.AddField(
            model_name='farm',
            name='productivity',
            field=models.FloatField(default='133'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region'),
        ),
    ]
