# Generated by Django 5.2.6 on 2025-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_remove_district_farm_remove_massive_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='massive_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
