# Generated by Django 5.2.6 on 2025-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_farm_massive_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
