# Generated by Django 5.2.6 on 2025-09-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_farmexcelupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
