# Generated by Django 5.2.6 on 2025-09-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0008_alter_farm_location_alter_farm_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='INN',
            field=models.IntegerField(unique=True),
        ),
    ]
