# Generated by Django 5.2.6 on 2025-09-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0009_alter_farm_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='INN',
            field=models.CharField(unique=True),
        ),
    ]
