# Generated by Django 5.2.6 on 2025-09-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0010_alter_farm_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='neighborhood',
        ),
    ]
