# Generated by Django 5.2.6 on 2025-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0012_alter_district_crop_area_alter_district_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
