# Generated by Django 5.2.6 on 2025-09-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0015_alter_district_region_alter_district_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='region.district'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='massive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='region.massive'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='region.region'),
        ),
    ]
