# Generated by Django 5.2.6 on 2025-09-13 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0016_alter_farm_district_alter_farm_massive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='massive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='region.massive'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhoods', to=settings.AUTH_USER_MODEL),
        ),
    ]
