# Generated by Django 5.2.6 on 2025-09-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('r', 'region'), ('d', 'district'), ('m', 'massive'), ('n', 'neighborhood'), ('s', 'squad')], max_length=10),
        ),
    ]
