# Generated by Django 5.2.6 on 2025-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('r', 'region'), ('d', 'district'), ('m', 'massive'), ('n', 'neighborhood'), ('sd', 'squad'), ('sm', 'scalesman'), ('sh', 'shtab')], max_length=10),
        ),
    ]
