# Generated by Django 5.2.6 on 2025-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userexcelupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/users/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserExcelUpload',
            new_name='NeighborhoodExcelUpload',
        ),
    ]
