# Generated by Django 5.2.6 on 2025-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_squadexcelupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('r', 'region'), ('d', 'district'), ('m', 'massive'), ('n', 'neighborhood'), ('sd', 'squad'), ('sm', 'scalesman'), ('sh', 'shtab'), ('dr', 'driver')], max_length=10),
        ),
    ]
